version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
  jobs:
    post_checkout:
      - git fetch --unshallow || true
sphinx:
  configuration: doc/conf.py
python:
  install:
    - requirements: doc/requirements.txt
